---
title: "Mini_project_3"
author: "Zhu Shen"
date: "April 9, 2018"
output:
  html_document:
    code_folding: hide

---

```{r setup, include=FALSE}
# Open the necesary libraries 
# will install version 0.3.2
# install.packages("macleish")
library(tidyverse)
library(sf)
#devtools::install_github("beanumber/macleish")
library(macleish)
library(RColorBrewer)
library(leaflet)
```

```{r, warning = FALSE, message = FALSE}
# Define the function that returns the difficulty level of a trail
hiking_diff <- function(x){
  if (x<=1){
    return ("Easy")
  }
  if (x> 1 & x<= 10){
    return ("Moderate")
  }
  if (x> 10){
    return ("Hard")
  }
}


# Save the campsite data as a tibble 
campsite <- tribble(
  ~point, ~lon, ~lat,
  "Group Campsite", -72.678154, 42.450976, 
  "Remote Campite", -72.674732, 42.458570, 
  "Remote campsite", -72.679581, 42.458549
)
# Convert the tibble into a sf dataframe
camp_sf <- campsite %>%
  st_as_sf(coords = c("lon", "lat"))

# Save the parking data as a tibble 
parking <- tribble(
  ~point, ~lon, ~lat,
  "Parking", -72.680663, 42.448013
)
# Convert the tibble into a sf dataframe
parking_sf <- parking %>%
  st_as_sf(coords = c("lon", "lat"))
```

```{r, warning = FALSE, message = FALSE}
# Make sure that the layer has the same projection 
elevation <- macleish_layers[["contours_30ft"]] %>%
  st_transform(4326) 

# Find all the intersection point of trails and contours 
trail_intersex <- elevation %>%
  st_intersection(macleish_layers[["trails"]])
#head(trail_intersex)
# Convert the type to be POINT  
trail_intersex_point <- st_cast(trail_intersex, "POINT")

# Calculate the length of each trail in miles 
# 1 mile = 1609.34 meters
trails <- macleish_layers[["trails"]] %>%
  mutate(length = st_length(geometry)) %>%
  group_by(name) %>%
  summarize(total_length_mile = sum(length)/1609.34)

# Next we want to find the change in elevation of these trails in feet 
macleish_rise <- trail_intersex %>%
  group_by(name) %>%
  summarise(elevation_range = max(CONTOUR_FT)-min(CONTOUR_FT), 
            stand_dev = sd(CONTOUR_FT))

# Define the palette for categorical data 
factpal <- colorFactor(topo.colors(9), trails$name, 
                       palette = c('#228B22','#FFFF00','#00FFFF','#FFB90F','#6495ED', '#FF0000','#FF82AB','#836FFF','#FFBBFF'))

# Create the map with different background themes and three layers that are controlled by the button 
# There is a label showing the name of each trail
# If you click the intersection point, the height and the trail name will pop up
map <- 
  leaflet() %>%
  addTiles(group = "OSM (default)") %>%
  addProviderTiles(providers$Thunderforest.Landscape, group = "Landscape") %>%
  addProviderTiles(providers$Stamen.TonerLite, group = "Toner Lite") %>%
  addPolylines(data = macleish_layers[["boundary"]], weight = 3, color = "green", fill = "green", group = "Outline") %>%
  addPolylines(data = elevation, weight = 2, color = "black", group = "Outline") %>%
  addPolylines(data = trails, weight = 3, color = ~factpal(trails$name), opacity = 1, label = ~name, group = "Trails") %>%
  addPolygons(data = macleish_layers[["buildings"]], color = "black", stroke = FALSE, label = "Buildings") %>%
  addCircleMarkers(data = st_cast(trail_intersex, "POINT"), color = "blue",radius = 3, popup = ~paste("Trail: ",name,"<br/>Elevation: ", CONTOUR_FT, "ft"), group = "Intersection Points") %>%
  addCircleMarkers(data = camp_sf, color = "brown",radius = 3, label = ~point, group = "Campsites") %>%
  addCircleMarkers(data = parking_sf, color = "red",radius = 3, label = ~point, group = "Parking") %>%
  addLayersControl(
    baseGroups = c("OSM (default)", "Landscape", "Toner Lite"),
    overlayGroups = c("Trails", "Outline", "Intersection Points", "Campsites", "Parking"),
    options = layersControlOptions(collapsed = FALSE)
  )


# Show the map
map

```

```{r, message = FALSE, warning = FALSE}
# Convert the spatial data sets into normal data frame 
df_1 <- as.data.frame(macleish_rise) %>%
  select(name, elevation_range, stand_dev)
df_2 <- as.data.frame(trails) %>%
  select(name, total_length_mile)

# use the full join to convert the data type of two columns 
df <- df_1 %>%
  full_join(df_2) %>%
  mutate(total_length_mile = as.numeric(total_length_mile), 
         elevation_range = as.numeric(elevation_range))

# Because there is some NA in the data set, in order to calculate the difficulty level
df$elevation_range[which(is.na(df$elevation_range))] <- 1
df$elevation_range[which(df$elevation_range == 0)] <- 1

# Calculate the difficulty index = sqrt(2*elevation change*total length in mile))
df <- df %>%
  mutate(diff_index =sqrt(2*elevation_range*total_length_mile)) %>%
  arrange(name)

# Apply the function that categorize each trail by their difficulty level
df$diff_cat <- lapply(df$diff_index, FUN = hiking_diff)

# Join two st data set by trials' names 
macleish_data <- trails %>%
  st_join(macleish_rise, join = st_contains, left = TRUE) %>%
  arrange(name.x)

# Change the macleish_data elevation change, diff_index and diff_cat
macleish_data <- macleish_data %>%
  mutate(elevation_range = df$elevation_range, 
         diff_index = df$diff_index, 
         diff_cat = df$diff_cat)

# Split the data into three sub-data set of "Easy", "Moderate" and "Hard"
easy <- macleish_data %>%
  filter(diff_cat == "Easy")
moderate <- macleish_data %>%
  filter(diff_cat == "Moderate")
hard <- macleish_data %>%
  filter(diff_cat == "Hard")

# Create the map with different background themes and three layers("Easy", "Moderate" and "Hard") that are controlled by the button 
# There is a label showing the name of each trail
# If you click the intersection point, the height and the trail name will pop up
map_cat <- 
  leaflet() %>%
  addTiles(group = "OSM (default)") %>%
  addProviderTiles(providers$Thunderforest.Landscape, group = "Landscape") %>%
  addProviderTiles(providers$Stamen.TonerLite, group = "Toner Lite") %>%
  addPolylines(data = macleish_layers[["boundary"]], weight = 3, color = "green", fill = "green", group = "Outline") %>%
  addPolylines(data = elevation, weight = 2, color = "black", group = "Outline") %>%
  addPolylines(data = easy, weight = 3, color = "yellow", opacity = 1, label = ~name.x, group = "Easy") %>%
  addPolylines(data = moderate, weight = 3, color = "orange", opacity = 1, label = ~name.x, group = "Moderate") %>%
  addPolylines(data = hard, weight = 3, color = "red", opacity = 1, label = ~name.x, group = "Hard") %>%
  addCircleMarkers(data = macleish_layers[["challenge_courses"]], color = "green",radius = 3, label = ~paste("Challenge Course: ",cmt), group = "Challenge Course") %>%
  addPolygons(data = macleish_layers[["buildings"]], color = "black", stroke = FALSE, label = "Buildings") %>%
  addCircleMarkers(data = st_cast(trail_intersex, "POINT"), color = "blue",radius = 2, popup = ~paste("Trail: ",name,"<br/>Elevation: ", CONTOUR_FT, "ft"), group = "Intersection Points") %>%
  addCircleMarkers(data = camp_sf, color = "brown",radius = 3, label = ~point, group = "Campsites") %>%
  addCircleMarkers(data = parking_sf, color = "red",radius = 3, label = ~point, group = "Parking") %>%
  addLayersControl(
    baseGroups = c("OSM (default)", "Landscape", "Toner Lite"),
    overlayGroups = c("Outline", "Intersection Points", "Easy", "Moderate", "Hard", "Challenge Course", "Campsites", "Parking"),
    options = layersControlOptions(collapsed = FALSE)
  )
# Show the leaflet map

map_cat


```


